from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path

import pytest
import tools.import_versions as import_versions

from danks_repo.repository import (
    collect_source_files,
    copy_snapshot,
    sha256_file,
    write_generation_manifest,
)
from tools.import_versions import (
    V3_INCLUDED_TESTS,
    build_text_replacements,
    v3_excluded_relative_paths,
)


def test_importer_uses_public_v1_v2_v3_names(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    assert hasattr(import_versions, "V3_INCLUDED_TESTS")
    assert hasattr(import_versions, "v3_excluded_relative_paths")

    source = tmp_path / "source"
    overlay = tmp_path / "overlay.py"
    argv = [
        "import_versions.py",
        "--v1-source",
        str(source),
        "--v2-source",
        str(source),
        "--v3-source",
        str(source),
        "--v3-model-source",
        str(overlay),
        "--v3-ppo-source",
        str(overlay),
        "--v3-train-ppo-source",
        str(overlay),
        "--redact-prefix",
        "/private/source",
    ]
    monkeypatch.setattr("sys.argv", argv)
    args = import_versions.parse_args()
    assert (args.v1_source, args.v2_source, args.v3_source) == (source, source, source)


def write_file(root: Path, relative: str, content: bytes = b"source\n") -> Path:
    path = root / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content)
    return path


def test_collect_source_files_keeps_only_code_and_source_configuration(tmp_path: Path) -> None:
    source = tmp_path / "source"
    kept = {
        "pkg/model.py",
        "native/engine.cpp",
        "native/engine.h",
        "native/detail.hpp",
        "native/compat.c",
        "server/main.go",
        "scripts/run.sh",
        "config/public.json",
        "config/train.toml",
        "config/base.yaml",
        "config/extra.yml",
        "Makefile",
        "CMakeLists.txt",
        "requirements.txt",
        "go.mod",
        "go.sum",
    }
    for relative in kept:
        write_file(source, relative)

    rejected = {
        "README.md",
        "docs/internal.md",
        "docs/design.docx",
        "reports/result.pdf",
        "notes/private.txt",
        ".env",
        "models/policy.pt",
        "weights/policy.onnx",
        "arrays/table.npz",
        "lib/runtime.so",
        "wheels/runtime.whl",
        "archives/source.zip",
        "logs/train.log",
        "checkpoints/state.json",
        "eval_runs/result.json",
        ".venv/lib/site.py",
        "pkg/__pycache__/model.pyc",
        ".DS_Store",
        ".build/generated.c",
        ".compile-toolchain/include/toolchain.h",
        ".go-toolchain/src/tool.go",
        ".codex_removed/old.py",
        ".claude_resources.json",
        "native/generated.c",
        "image.png",
    }
    for relative in rejected:
        content = b"/* Generated by Cython 3.0 */\n" if relative == "native/generated.c" else b"source\n"
        write_file(source, relative, content)

    actual = {path.as_posix() for path in collect_source_files(source)}
    assert actual == kept


def test_collect_source_files_does_not_follow_symlinks(tmp_path: Path) -> None:
    if not hasattr(os, "symlink"):
        pytest.skip("symlinks are unavailable")

    source = tmp_path / "source"
    outside = write_file(tmp_path, "outside/secret.py", b"private\n")
    write_file(source, "pkg/real.py")
    (source / "linked.py").symlink_to(outside)
    (source / "linked_dir").symlink_to(outside.parent, target_is_directory=True)

    assert [path.as_posix() for path in collect_source_files(source)] == ["pkg/real.py"]


def test_project_top_level_allowlist_fails_closed(tmp_path: Path) -> None:
    source = tmp_path / "source"
    write_file(source, "pkg/model.py")
    write_file(source, "config/public.yaml")
    write_file(source, "Makefile")
    write_file(source, "evals/result.json")
    write_file(source, "vendor/third_party.cpp")
    write_file(source, "tmp/scratch.py")

    actual = collect_source_files(
        source,
        allowed_top_level={"pkg", "config", "Makefile"},
    )
    assert [path.as_posix() for path in actual] == [
        "Makefile",
        "config/public.yaml",
        "pkg/model.py",
    ]


def test_copy_snapshot_and_manifest_are_sorted_and_content_addressed(tmp_path: Path) -> None:
    repository = tmp_path / "DanKS"
    source = tmp_path / "upstream"
    write_file(source, "z.py", b"z\n")
    write_file(source, "a.py", b"a\n")
    write_file(source, "README.md", b"private docs\n")
    destination = repository / "generations" / "v1" / "source"

    copied = copy_snapshot(source, destination, repository)
    assert [path.as_posix() for path in copied] == ["a.py", "z.py"]
    assert not (destination / "README.md").exists()

    manifest_path = write_generation_manifest(
        repository,
        "v1",
        source_label="frozen-source-snapshot",
    )
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert manifest["generation"] == "v1"
    assert manifest["source"] == "frozen-source-snapshot"
    assert "upstream" not in manifest_path.read_text(encoding="utf-8")
    assert [item["path"] for item in manifest["files"]] == ["a.py", "z.py"]
    assert manifest["files"][0] == {
        "path": "a.py",
        "sha256": hashlib.sha256(b"a\n").hexdigest(),
        "size": 2,
    }
    assert sha256_file(destination / "z.py") == hashlib.sha256(b"z\n").hexdigest()


def test_copy_snapshot_refuses_destination_outside_generations(tmp_path: Path) -> None:
    repository = tmp_path / "DanKS"
    source = tmp_path / "source"
    write_file(source, "model.py")

    with pytest.raises(ValueError, match="generations"):
        copy_snapshot(source, repository / "public", repository)


def test_copy_snapshot_refuses_nonempty_destination(tmp_path: Path) -> None:
    repository = tmp_path / "DanKS"
    source = tmp_path / "source"
    write_file(source, "model.py")
    destination = repository / "generations" / "v3" / "source"
    write_file(destination, "existing.py")

    with pytest.raises(FileExistsError, match="not empty"):
        copy_snapshot(source, destination, repository)


def test_copy_snapshot_can_sanitize_private_path_prefixes(tmp_path: Path) -> None:
    repository = tmp_path / "DanKS"
    source = tmp_path / "source"
    write_file(
        source,
        "pkg/paths.py",
        b'linux = "/srv/private/alice/project"\nmac = "/Users/alice/project"\n',
    )
    destination = repository / "generations" / "v3" / "source"

    copy_snapshot(
        source,
        destination,
        repository,
        text_replacements={
            b"/srv/private/alice": b"/workspace/danks",
            b"/Users/alice": b"/workspace/danks",
        },
    )

    content = (destination / "pkg/paths.py").read_bytes()
    assert b"/home/share/user/" not in content
    assert b"/Users/" not in content
    assert content.count(b"/workspace/danks/project") == 2


def test_importer_builds_anonymous_replacements_from_cli_prefixes() -> None:
    assert build_text_replacements(["/srv/private/alice", "/Users/alice"]) == {
        b"/srv/private/alice": b"/workspace/danks",
        b"/Users/alice": b"/workspace/danks",
    }
    with pytest.raises(ValueError, match="absolute paths"):
        build_text_replacements(["/"])


def test_copy_snapshot_supports_curated_exclusions_and_overlays(tmp_path: Path) -> None:
    repository = tmp_path / "DanKS"
    source = tmp_path / "source"
    overlay = write_file(tmp_path, "overlay/model.py", b"v3 model\n")
    write_file(source, "training/model.py", b"later experimental model\n")
    write_file(source, "training/v13_model.py", b"not part of V3\n")
    write_file(source, "tests/test_v13.py", b"not part of V3\n")
    destination = repository / "generations" / "v3" / "source" / "DanRL_retrieval"

    copied = copy_snapshot(
        source,
        destination,
        repository,
        excluded_relative_paths={"training/v13_model.py", "tests/test_v13.py"},
        overlay_files={"training/model.py": overlay},
    )

    assert [path.as_posix() for path in copied] == ["training/model.py"]
    assert (destination / "training/model.py").read_bytes() == b"v3 model\n"
    assert not (destination / "training/v13_model.py").exists()


def test_v3_public_exclusions_keep_only_supported_core_tests(tmp_path: Path) -> None:
    source = tmp_path / "v3"
    for test_name in V3_INCLUDED_TESTS:
        write_file(source, f"tests/{test_name}")
    write_file(source, "tests/test_platform_danks_training.py")
    write_file(source, "tests/test_v13_structured_tactics.py")
    write_file(source, "training/v13_model.py")

    excluded = v3_excluded_relative_paths(source)

    assert "tests/test_platform_danks_training.py" in excluded
    assert "tests/test_v13_structured_tactics.py" in excluded
    assert "training/v13_model.py" in excluded
    assert not {
        f"tests/{test_name}" for test_name in V3_INCLUDED_TESTS
    } & excluded


def test_v3_public_test_set_excludes_version_or_native_build_coupled_tests() -> None:
    assert not {
        "test_native_actor_core.py",
        "test_native_cpp.py",
        "test_partitioner.py",
        "test_ppo_v2_network.py",
        "test_ranker.py",
        "test_tactical_sampling.py",
    } & V3_INCLUDED_TESTS
