"""Shared repository contract and path-safety helpers."""

from __future__ import annotations

import hashlib
import json
import os
import shutil
from pathlib import Path


GENERATIONS = ("v1", "v2", "v3")

REQUIRED_ROOT_PATHS = (
    "README.md",
    "ARCHITECTURE.md",
    "CHANGELOG.md",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "LICENSE",
    "NOTICE",
    "Makefile",
    "pyproject.toml",
    ".gitignore",
    ".github/workflows/ci.yml",
    "docs/REPOSITORY_LAYOUT.md",
    "docs/REPRODUCIBILITY.md",
    "docs/MODEL_WEIGHTS.md",
    "docs/LICENSING.md",
    "docs/QUICKSTART.md",
    "docs/SOURCE_MAP.md",
    "danks_repo/__main__.py",
)

REQUIRED_GENERATION_PATHS = tuple(
    path
    for generation in GENERATIONS
    for path in (
        f"generations/{generation}/source",
        f"generations/{generation}/manifest.json",
        f"generations/{generation}/README.md",
    )
)

FORBIDDEN_DIRECTORY_NAMES = frozenset(
    {
        ".git",
        ".idea",
        ".mypy_cache",
        ".pytest_cache",
        ".venv",
        ".vscode",
        "__pycache__",
        "backups",
        "checkpoints",
        "data",
        "datasets",
        "dist",
        "docs",
        "eval",
        "eval_runs",
        "logs",
        "models",
        "node_modules",
        "runs",
        "snapshots",
        "toolchains",
        "venv",
        "wheels",
    }
)

FORBIDDEN_SUFFIXES = frozenset(
    {
        ".7z",
        ".bin",
        ".ckpt",
        ".doc",
        ".docx",
        ".dylib",
        ".env",
        ".gz",
        ".joblib",
        ".log",
        ".md",
        ".npy",
        ".npz",
        ".onnx",
        ".pdf",
        ".pickle",
        ".pkl",
        ".pt",
        ".pth",
        ".rar",
        ".so",
        ".tar",
        ".txt",
        ".whl",
        ".zip",
    }
)

ALLOWED_SOURCE_SUFFIXES = frozenset(
    {
        ".c",
        ".cc",
        ".cmake",
        ".cpp",
        ".cu",
        ".cuh",
        ".go",
        ".h",
        ".hh",
        ".hpp",
        ".json",
        ".py",
        ".pyi",
        ".sh",
        ".toml",
        ".yaml",
        ".yml",
    }
)

ALLOWED_SOURCE_FILENAMES = frozenset(
    {
        "CMakeLists.txt",
        "Dockerfile",
        "Makefile",
        "go.mod",
        "go.sum",
        "setup.cfg",
    }
)


def assert_safe_generation_destination(root: Path, destination: Path) -> Path:
    """Return a resolved generation destination or reject path escape."""

    root = root.resolve()
    generations_root = (root / "generations").resolve()
    destination = destination.resolve()
    if destination == generations_root or generations_root not in destination.parents:
        raise ValueError("destination must stay below the repository generations directory")
    return destination


def _is_allowed_source_file(relative_path: Path) -> bool:
    if any(part.startswith(".") for part in relative_path.parts):
        return False
    if any(part in FORBIDDEN_DIRECTORY_NAMES for part in relative_path.parts[:-1]):
        return False
    if relative_path.name == ".DS_Store" or relative_path.name.startswith("._"):
        return False
    if relative_path.name in ALLOWED_SOURCE_FILENAMES:
        return True
    if relative_path.name.startswith("requirements") and relative_path.suffix == ".txt":
        return True
    return (
        relative_path.suffix.lower() in ALLOWED_SOURCE_SUFFIXES
        and relative_path.suffix.lower() not in FORBIDDEN_SUFFIXES
    )


def _is_generated_source_file(path: Path) -> bool:
    if path.suffix.lower() not in {".c", ".cc", ".cpp"}:
        return False
    with path.open("rb") as stream:
        header = stream.read(256)
    return b"Generated by Cython" in header


def collect_source_files(
    source_root: Path,
    *,
    allowed_top_level: set[str] | frozenset[str] | None = None,
    excluded_relative_paths: set[str] | frozenset[str] | None = None,
) -> list[Path]:
    """Return sorted relative paths accepted by the public code boundary."""

    source_root = source_root.resolve()
    if not source_root.is_dir():
        raise NotADirectoryError(source_root)
    if allowed_top_level is not None:
        allowed_top_level = frozenset(allowed_top_level)
        if any(not name or "/" in name or "\\" in name or name.startswith(".") for name in allowed_top_level):
            raise ValueError("top-level allowlist entries must be plain public names")
    excluded = frozenset(excluded_relative_paths or ())
    if any(
        not name
        or Path(name).is_absolute()
        or ".." in Path(name).parts
        or Path(name).as_posix() != name
        for name in excluded
    ):
        raise ValueError("excluded paths must be normalized relative POSIX paths")

    selected: list[Path] = []
    for directory, directory_names, file_names in os.walk(source_root, followlinks=False):
        current = Path(directory)
        directory_names[:] = sorted(
            name
            for name in directory_names
            if name not in FORBIDDEN_DIRECTORY_NAMES
            and not name.startswith(".")
            and not (current / name).is_symlink()
            and name != ".DS_Store"
            and (
                current != source_root
                or allowed_top_level is None
                or name in allowed_top_level
            )
        )
        for name in sorted(file_names):
            path = current / name
            if path.is_symlink():
                continue
            relative_path = path.relative_to(source_root)
            if allowed_top_level is not None and relative_path.parts[0] not in allowed_top_level:
                continue
            if relative_path.as_posix() in excluded:
                continue
            if _is_allowed_source_file(relative_path) and not _is_generated_source_file(path):
                selected.append(relative_path)
    return sorted(selected, key=lambda path: path.as_posix())


def copy_snapshot(
    source_root: Path,
    destination: Path,
    repository_root: Path,
    *,
    allowed_top_level: set[str] | frozenset[str] | None = None,
    excluded_relative_paths: set[str] | frozenset[str] | None = None,
    overlay_files: dict[str, Path] | None = None,
    text_replacements: dict[bytes, bytes] | None = None,
) -> list[Path]:
    """Copy a filtered snapshot into a new, empty generation source directory."""

    source_root = source_root.resolve()
    destination = assert_safe_generation_destination(repository_root, destination)
    if destination.exists() and any(destination.iterdir()):
        raise FileExistsError(f"snapshot destination is not empty: {destination}")
    destination.mkdir(parents=True, exist_ok=True)

    selected = collect_source_files(
        source_root,
        allowed_top_level=allowed_top_level,
        excluded_relative_paths=excluded_relative_paths,
    )
    replacements = sorted((text_replacements or {}).items(), key=lambda item: item[0])
    if any(not source for source, _ in replacements):
        raise ValueError("replacement source markers must not be empty")
    for relative_path in selected:
        target = destination / relative_path
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source_root / relative_path, target, follow_symlinks=False)
        if replacements:
            content = target.read_bytes()
            sanitized = content
            for source, replacement in replacements:
                sanitized = sanitized.replace(source, replacement)
            if sanitized != content:
                target.write_bytes(sanitized)
    selected_names = {path.as_posix() for path in selected}
    for relative_name, overlay_source in sorted((overlay_files or {}).items()):
        relative_path = Path(relative_name)
        if relative_name not in selected_names or relative_path.as_posix() != relative_name:
            raise ValueError(f"overlay target must replace a selected source file: {relative_name}")
        overlay_source = overlay_source.resolve()
        if overlay_source.is_symlink() or not overlay_source.is_file():
            raise ValueError(f"overlay source must be a regular file: {overlay_source}")
        target = destination / relative_path
        shutil.copy2(overlay_source, target, follow_symlinks=False)
        if replacements:
            content = target.read_bytes()
            sanitized = content
            for source, replacement in replacements:
                sanitized = sanitized.replace(source, replacement)
            if sanitized != content:
                target.write_bytes(sanitized)
    return selected


def sha256_file(path: Path) -> str:
    """Hash a regular file without loading it wholly into memory."""

    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_generation_manifest(
    repository_root: Path,
    generation: str,
    *,
    source_label: str,
) -> Path:
    """Write a deterministic manifest for one imported generation."""

    if generation not in GENERATIONS:
        raise ValueError(f"unknown generation: {generation}")
    repository_root = repository_root.resolve()
    generation_root = repository_root / "generations" / generation
    source_root = generation_root / "source"
    if not source_root.is_dir():
        raise NotADirectoryError(source_root)

    files = []
    for relative_path in collect_source_files(source_root):
        path = source_root / relative_path
        files.append(
            {
                "path": relative_path.as_posix(),
                "sha256": sha256_file(path),
                "size": path.stat().st_size,
            }
        )
    manifest = {
        "schema_version": 1,
        "generation": generation,
        "source": source_label,
        "files": files,
    }
    manifest_path = generation_root / "manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return manifest_path
